language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

      before_script:
        - git clone https://github.com/SFML/SFML && cd SFML
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - export SFML_ROOT=`pwd`
        - cd .. && mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..

      script: make

      after_script:
        - rm -rf SFML
