dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - libgl1-mesa-dev
            - libx11-dev
            - libx11-xcb-dev
            - libudev-dev
            - libglew-dev
            - libxrandr-dev
            - libjpeg8-dev
            - libfreetype6-dev
            - libopenal-dev
            - libflac++-dev
            - libvorbis-dev

      before_script:
        - export CXX=g++-6 && export CC=gcc-6
        - git clone https://github.com/SFML/SFML && cd SFML
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - export SFML_ROOT=`pwd`
        - ls
        - echo "$SFML_ROOT"
        - cd .. && mkdir build && cd build
        - ls
        - echo "$SFML_ROOT"
        - cmake -DCMAKE_BUILD_TYPE=Release ..

      script: make

      after_script:
        - rm -rf SFML
