language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6

      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..

      script: make
