language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - unzip

      before_script:
        - wget -O sfml.zip https://www.sfml-dev.org/files/SFML-2.4.2-windows-gcc-6.1.0-mingw-64-bit.zip
        - unzip sfml.zip
        - export SFML_ROOT=`pwd`
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..

      after_script:
        - rm sfml.zip
        
      script: make
